version: '3'
services:
#  nginx:
#    image: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ${HOME}/eshop/nginx/shared:/var/opt/eshop
#      - ./nginx.config:/etc/nginx/conf.d/default.conf

#  db:
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: "spring"
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./scripts/init-db-scripts:/docker-entrypoint-initdb.d
#      - mysql-test:/var/lib/mysql
#    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: spring
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db-scripts:/docker-entrypoint-initdb.d
      - postgres-test:/var/lib/postgresql/data

volumes:
  postgres-test: