version: '3'
services:
  cloud-config:
    image: registry.heroku.com/geek-spring-cloud-config/web:latest
    ports:
    - 8888:8888

  shop-admin-app:
    image: registry.heroku.com/geek-shop-admin-app/web:latest
    ports:
    - 8082:8082
    command: sh -c "/apps/wait-for-mysql.sh db 3306 && /apps/wait-for-mysql.sh cloud-config 8888 && /apps/entrypoint.sh"
    volumes:
      - ./storage:/apps/storage

  shop-picture-app:
    image: registry.heroku.com/geek-picture-service-app/web:latest
    ports:
    - 8081:8081
    command: sh -c "/apps/wait-for-mysql.sh db 3306 && /apps/wait-for-mysql.sh cloud-config 8888 && /apps/entrypoint.sh"
    volumes:
      - ./storage:/apps/storage

  shop-backend-app:
    image: registry.heroku.com/geek-shop-backend-api-app/web
    ports:
      - 8083:8083
    command: sh -c "/apps/wait-for-mysql.sh cloud-config 8888 && /apps/wait-for-mysql.sh rabbitmq 5672 && /apps/entrypoint.sh"

  shop-delivery:
    image: registry.heroku.com/geek-shop-delivery-service/web
    ports:
      - 8084:8084
    command: sh -c "/apps/wait-for-mysql.sh rabbitmq 5672 && /apps/entrypoint.sh"

  nginx:
    image: nginx
    ports:
      - 8085:8085
    volumes:
      - ./shop-frontend-app/dist/shop-frontend-app:/var/opt/eshop
      - ./nginx.config:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: "geek_eshop"
      MYSQL_USER: "spring"
      MYSQL_PASSWORD: "spring"
    ports:
      - 3308:3306
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
    - 5672:5672
    - 15672:15672

  redis:
    image: redis:latest
    ports:
    - 6379:6379

volumes:
  mysql-data: