version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./shop-frontend-app/dist/shop-frontend-app:/var/opt/eshop
      - ./nginx.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - shop-admin-app
      - shop-gateway

  cloud-config:
    image: spring-cloud-config
    ports:
    - "80"

  eureka-service:
    image: spring-eureka
    ports:
      - "80"

  shop-gateway:
    image: spring-cloud-gateway
    ports:
      - "80"

  shop-admin-app:
    image: shop-admin-app
    ports:
    - "80"
    volumes:
      - ${HOME}/eshop/pictures:/apps/pictures
    depends_on:
      - cloud-config

  shop-picture-app:
    image: picture-service-app
    ports:
    - "80"
    volumes:
      - ${HOME}/eshop/pictures:/apps/pictures

  shop-backend-app:
    image: shop-backend-api-app
    ports:
      - "80"

  shop-delivery:
    image: shop-delivery-service
    ports:
      - "80"

  db:
    image: mysql
    environment:
      MYSQL_USER: "spring"
      MYSQL_PASSWORD: "spring"
      MYSQL_DATABASE: "geek_eshop"
      MYSQL_ROOT_PASSWORD: "spring"
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
    - "5672"

  redis:
    image: redis:latest
    ports:
    - "6379"

volumes:
  mysql-data: