INSERT INTO categories (name) VALUES
    ('Оперативная память'),
    ('Жесткие диски'),
    ('Мониторы'),
    ('Принтеры'),
    ('Процессоры'),
    ('Видеокарты'),
    ('Материнские платы'),
    ('Смартфоны'),
    ('Планшеты');
GO

INSERT INTO products (name, cost, category_id) VALUES
    ('Процессор AMD Ryzen 5 3600 OEM', 14299, (SELECT id FROM categories WHERE categories.name = 'Процессоры')),
    ('Оперативная память AMD Radeon R5 Entertainment Series [R538G1601U2S-U] 8 ГБ', 2999, (SELECT id FROM categories WHERE categories.name = 'Оперативная память')),
    ('10.2" Планшет Apple iPad 2020 Wi-Fi 128 ГБ серый', 38999, (SELECT id FROM categories WHERE categories.name = 'Планшеты')),
    ('23.6" Монитор Acer K242HYLBBD черный', 9199, (SELECT id FROM categories WHERE categories.name = 'Мониторы')),
    ('Процессор Intel Core i5-10400F OEM', 11799, (SELECT id FROM categories WHERE categories.name = 'Процессоры')),
    ('Видеокарта GIGABYTE GeForce RTX 3060 GAMING OC (LHR) [GV-N3060GAMING OC-12GD Rev2.0]', 58999, (SELECT id FROM categories WHERE categories.name = 'Видеокарты')),
    ('Принтер лазерный Kyocera ECOSYS P2040dn', 22299, (SELECT id FROM categories WHERE categories.name = 'Принтеры')),
    ('1 ТБ Жесткий диск WD Blue [WD10EZEX]', 2999, (SELECT id FROM categories WHERE categories.name = 'Жесткие диски')),
    ('6.1" Смартфон Apple iPhone 12 128 ГБ фиолетовый', 67999, (SELECT id FROM categories WHERE categories.name = 'Смартфоны')),
    ('Материнская плата MSI Z490-A PRO', 11899, (SELECT id FROM categories WHERE categories.name = 'Материнские платы')),
    ('Принтер лазерный HP Laser 107r', 7999, (SELECT id FROM categories WHERE categories.name = 'Принтеры')),
    ('Процессор AMD Ryzen 5 3500X OEM', 11799, (SELECT id FROM categories WHERE categories.name = 'Процессоры')),
    ('Видеокарта Palit GeForce GTX 1660 DUAL [NE51660018J9-1161C]', 39999, (SELECT id FROM categories WHERE categories.name = 'Видеокарты')),
    ('23.5" Монитор Samsung S24F354FHI черный', 9399, (SELECT id FROM categories WHERE categories.name = 'Мониторы')),
    ('1 ТБ Жесткий диск Seagate 7200 BarraCuda [ST1000DM010]', 2899, (SELECT id FROM categories WHERE categories.name = 'Жесткие диски')),
    ('Оперативная память AMD Radeon R9 Gamer Series [R9S416G3206U2K] 16 ГБ', 6599, (SELECT id FROM categories WHERE categories.name = 'Оперативная память')),
    ('10.4" Планшет Huawei Matepad 128 ГБ серый', 23999, (SELECT id FROM categories WHERE categories.name = 'Планшеты')),
    ('6.53" Смартфон Xiaomi Redmi 9 32 ГБ серый', 10499, (SELECT id FROM categories WHERE categories.name = 'Смартфоны')),
    ('Принтер лазерный HP LaserJet Pro M15a', 8499, (SELECT id FROM categories WHERE categories.name = 'Принтеры')),
    ('2 ТБ Жесткий диск WD Purple [WD20PURZ]', 5999, (SELECT id FROM categories WHERE categories.name = 'Жесткие диски')),
    ('Материнская плата MSI B450M MORTAR MAX', 6999, (SELECT id FROM categories WHERE categories.name = 'Материнские платы')),
    ('Процессор AMD Ryzen 9 5900X BOX', 49299, (SELECT id FROM categories WHERE categories.name = 'Процессоры')),
    ('24" Монитор Samsung Odyssey G3 F24G35TFWI черный', 12999, (SELECT id FROM categories WHERE categories.name = 'Мониторы')),
    ('10.4" Планшет Samsung Galaxy Tab S6 Lite 64 ГБ серый', 24699, (SELECT id FROM categories WHERE categories.name = 'Планшеты')),
    ('Видеокарта MSI GeForce RTX 3080 Ti VENTUS 3X 12G [RTX 3080 Ti VENTUS 3X 12G]', 157999, (SELECT id FROM categories WHERE categories.name = 'Видеокарты')),
    ('Материнская плата GIGABYTE B550 AORUS ELITE V2', 10499, (SELECT id FROM categories WHERE categories.name = 'Материнские платы')),
    ('6.1" Смартфон Apple iPhone 11 128 ГБ красный', 46049, (SELECT id FROM categories WHERE categories.name = 'Смартфоны')),
    ('4 ТБ Жесткий диск Seagate 5900 SkyHawk [ST4000VX007]', 10499, (SELECT id FROM categories WHERE categories.name = 'Жесткие диски')),
    ('Оперативная память Kingston HyperX FURY Black [HX437C19FB3K2/32] 32 ГБ', 17799, (SELECT id FROM categories WHERE categories.name = 'Оперативная память')),
    ('Процессор Intel Core i5-10400F BOX', 14799, (SELECT id FROM categories WHERE categories.name = 'Процессоры'));
GO