server:
  port: 8082

authService:
  baseUrl: http://localhost:8080

picture:
  storage:
    path: ${HOME}/eshop/pictures

spring:
  webflux:
    base-path: /api/v1/pictures
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop_pictures
    driver-class-name: org.postgresql.Driver
    username: pictures
    password: pictures
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          eshop-pictures-oidc:
            provider: spring
            client-id: eshop-pictures
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8082/login/oauth2/code/eshop-pictures-oidc"
            scope: openid
            client-name: eshop-pictures-oidc
        provider:
          spring:
            issuer-uri: ${authService.baseUrl}

log4jdbc:
  drivers: ${spring.datasource.driver-class-name}
  auto:
    load:
      popular:
        drivers: false

logging:
  level:
    jdbc:
      sqltiming: INFO
      resultsettable: DEBUG
      sqlonly: ERROR
      audit: ERROR
      resultset: ERROR

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    org.springframework.security: debug
#    org.springframework.security.oauth2: debug